export PATH="$HOME/.local/bin:$PATH"

if [ -f "$HOME/.config/dev-bootstrap/proxy.env" ]; then
  source "$HOME/.config/dev-bootstrap/proxy.env"
fi

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git npm node sudo)

if [ -f "$ZSH/oh-my-zsh.sh" ]; then
  source "$ZSH/oh-my-zsh.sh"
fi

alias ll='ls -alF'
alias la='ls -A'
alias gs='git status'
